name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - mai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        uses: actions/configure-pages@v4
        with:
          enablement: true # Automatically enable GitHub Pages if not enabled
